name: Daily US Stock Signal

on:
  schedule:
    - cron: '10 22 * * *'  # 매일 오전 7:10 (KST) == 22:10 (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install yfinance requests
      - name: Run stock timer
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: python main_ntn.py